# Generated by Django 4.1.5 on 2023-01-25 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0003_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="place",
            name="photo",
            field=models.ImageField(null=True, upload_to=""),
        ),
        migrations.DeleteModel(
            name="Photo",
        ),
    ]
