# Generated by Django 4.1.5 on 2023-02-01 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0004_place_photo_delete_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="place",
            name="photo",
            field=models.ImageField(upload_to=""),
        ),
    ]
