# Generated by Django 4.1.6 on 2023-02-10 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_alter_place_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
