# Generated by Django 4.1.6 on 2023-02-15 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_alter_place_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='qr_img',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
