# Generated by Django 4.1.6 on 2023-02-15 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='P_number',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
