# Generated by Django 4.1.6 on 2023-02-15 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_p_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='P_number',
        ),
    ]
